q("talkPage.init", {
  el: "[data-talk-page]",
  __INITIAL_DATA__: {
    comments: { id: 28839, count: 1, talk_id: 51634 },
    threadId: 28839,
    requested_language_english_name: "English",
    current_talk: "51634",
    description:
      "Tashka and Laura Yawanawá lead the Yawanawá people in Acre, Brazil -- a tribe that stewards almost 500,000 acres of Amazon rainforest. As footage of the Amazon burning shocks the world's consciousness, Tashka and Laura call for us to transform this moment into an opportunity to support indigenous people who have the experience, knowledge and tools needed to protect the land.",
    event: "We the Future",
    language: "en",
    language_swap: false,
    name: "Tashka and Laura Yawanawá: The Amazon belongs to humanity -- let's protect it together",
    slug: "tashka_and_laura_yawanawa_the_amazon_belongs_to_humanity_let_s_protect_it_together",
    series_slug: null,
    speakers: [
      {
        id: "2101",
        slug: "tashka_yawanawa",
        is_published: true,
        firstname: "Tashka and Laura",
        lastname: "Yawanawá",
        middleinitial: "",
        title: "",
        description: "Leaders of the Yawanawá",
        photo_url: "https://pe.tedcdn.com/images/ted/57e42c162b1c6e1dea28ef647852b2bc3296ce7d_254x191.jpg",
        whatotherssay:
          "Tashka inherently understands the forces at work in both his and the Western worlds. As a result, he serves as an unusually effective bridge between indigenous groups and the outside.",
        whotheyare:
          "Chief Tashka Yawanawá and Laura Yawanawá represent the critical perspective often missed in the discussions about the future of indigenous people in Brazil: that of the indigenous people themselves.",
        whylisten:
          "<p>For Tashka and Laura Yawanaw&aacute;, leaders of the Yawanaw&aacute; people living in the Acre region of Brazil, engagement with the world begins with his people&rsquo;s right to self-determination and self-worth.</p><p>The son of a former leader of the Yawanaw&aacute;, as a boy Tashka witnessed the near annihilation of his culture by the New Tribes Mission and by the pressure of economic interests. He studied in the United States and visited other indigenous communities. With other tribal leaders in the Amazon, he is working to restore dignity, identity and a sustainable economic future to indigenous populations, founded on their own values, culture and definition of prosperity.</p>",
      },
    ],
    url: "https://www.ted.com/talks/tashka_and_laura_yawanawa_the_amazon_belongs_to_humanity_let_s_protect_it_together",
    viewed_count: 13755,
    talks: [
      {
        recommendations: null,
        more_resources: [],
        corrections: [],
        has_citations: true,
        take_action: [
          {
            status: "approved",
            blurb: "**Learn more** about the Yawanawá Life Plan.",
            link_url: "https://www.forest-trends.org/publications/yawanawa-life-plan/",
            visible_url: "forest-trends.org",
            start_at: null,
            end_at: null,
            published: true,
            eyebrow: "",
            type: "take_action",
            verb: "learn",
          },
          {
            status: "approved",
            blurb: "**Follow** the Yawanawás on Twitter.",
            link_url: "https://twitter.com/yawanawa",
            visible_url: "@yawanawa",
            start_at: null,
            end_at: null,
            published: true,
            eyebrow: null,
            type: "take_action",
            verb: "follow",
          },
        ],
        explore_cta_experiment: {},
        curator_approved: true,
        description:
          "Tashka and Laura Yawanawá lead the Yawanawá people in Acre, Brazil -- a tribe that stewards almost 500,000 acres of Amazon rainforest. As footage of the Amazon burning shocks the world's consciousness, Tashka and Laura call for us to transform this moment into an opportunity to support indigenous people who have the experience, knowledge and tools needed to protect the land.",
        downloads: {
          id: 51634,
          languages: [{ languageName: "English", endonym: "English", languageCode: "en", ianaCode: "en", isRtl: false }],
          nativeDownloads: {
            low: "https://download.ted.com/talks/TashkaYawanawa_2019S-light.mp4?apikey=acme-roadrunner",
            medium: "https://download.ted.com/talks/TashkaYawanawa_2019S.mp4?apikey=acme-roadrunner",
            high: "https://download.ted.com/talks/TashkaYawanawa_2019S-480p.mp4?apikey=acme-roadrunner",
          },
          subtitledDownloads: {
            en: {
              name: "English",
              low: "https://download.ted.com/talks/TashkaYawanawa_2019S-low-en.mp4?apikey=acme-roadrunner",
              high: "https://download.ted.com/talks/TashkaYawanawa_2019S-480p-en.mp4?apikey=acme-roadrunner",
            },
          },
          audioDownload: null,
        },
        duration: 352.0,
        event: "We the Future",
        institute_partner_name: null,
        salon_partner_name: null,
        event_badge: null,
        is_featured: true,
        hero: "https://s3.amazonaws.com/talkstar-photos/uploads/1ac77314-8f3a-41e7-b43d-49574dd40db6/TashkaYawanawa_2019S-embed.jpg",
        hero_load: "https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/1ac77314-8f3a-41e7-b43d-49574dd40db6/TashkaYawanawa_2019S-embed.jpg?q=50&w=15",
        id: "51634",
        player_talks: [
          {
            id: "51634",
            mediaIdentifier: "TashkaYawanawa_2019S",
            duration: 352.0,
            languages: [{ languageName: "English", endonym: "English", languageCode: "en", ianaCode: "en", isRtl: false }],
            nativeLanguage: "en",
            isSubtitleRequired: false,
            introDuration: 11.82,
            adDuration: 3.33,
            postAdDuration: 0.83,
            resources: {
              h264: [{ bitrate: 180, file: "https://pc.tedcdn.com/talk/stream/2019S/Blank/TashkaYawanawa_2019S-180k.mp4?dnt" }],
              hls: {
                adUrl:
                  "https://pubads.g.doubleclick.net/gampad/ads?ciu_szs=300x250%2C512x288%2C120x60%2C320x50%2C6x7%2C6x8&correlator=%5Bcorrelator%5D&cust_params=event%3DWe%2Bthe%2BFuture%26id%3D51634%26tag%3Dcommunity%2Cconservation%2Cindigenous%2Bpeoples%2Chumanity%2Cactivism%2Csociety%2Csocial%2Bchange%2CSouth%2BAmerica%26talk%3Dtashka_and_laura_yawanawa_the_amazon_belongs_to_humanity_let_s_protect_it_together%26year%3D2019&env=vp&gdfp_req=1&impl=s&iu=%2F5641%2Fmobile%2Fios%2Fweb&output=xml_vast2&sz=640x360&unviewed_position_start=1&url=%5Breferrer%5D",
                maiTargeting: {
                  id: "51634",
                  talk: "tashka_and_laura_yawanawa_the_amazon_belongs_to_humanity_let_s_protect_it_together",
                  tag: "community,conservation,indigenous peoples,humanity,activism,society,social change,South America",
                  year: "2019",
                  event: "We the Future",
                },
                stream: "https://hls.ted.com/talks/51634.m3u8",
                metadata: "https://hls.ted.com/talks/51634.json",
              },
            },
            targeting: {
              id: "51634",
              talk: "tashka_and_laura_yawanawa_the_amazon_belongs_to_humanity_let_s_protect_it_together",
              tag: "community,conservation,indigenous peoples,humanity,activism,society,social change,South America",
              year: "2019",
              event: "We the Future",
            },
            canonical: "https://www.ted.com/talks/tashka_and_laura_yawanawa_the_amazon_belongs_to_humanity_let_s_protect_it_together",
            name: "Tashka and Laura Yawanawá: The Amazon belongs to humanity -- let's protect it together",
            title: "The Amazon belongs to humanity -- let's protect it together",
            speaker: "Tashka and Laura Yawanawá",
            thumb: "https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/1ac77314-8f3a-41e7-b43d-49574dd40db6/TashkaYawanawa_2019S-embed.jpg?quality=89&w=600",
            slug: "tashka_and_laura_yawanawa_the_amazon_belongs_to_humanity_let_s_protect_it_together",
            event: "We the Future",
            published: 1572968989,
          },
        ],
        recorded_at: "2019-09-24T00:00:00.000+00:00",
        related_talks: [
          {
            id: "2528",
            hero: "https://s3.amazonaws.com/talkstar-photos/uploads/bcfbdc86-f78e-4d6d-b945-5b138527cc26/KeoluFox_2016U-embed.jpg",
            speaker: "Keolu Fox",
            title: "Why genetic research must be more diverse",
            duration: 408.0,
            slug: "keolu_fox_why_genetic_research_must_be_more_diverse",
            viewed_count: 920532,
          },
          {
            id: "12800",
            hero: "https://s3.amazonaws.com/talkstar-photos/uploads/8af195ec-47bc-4ef8-a906-ee8efed3e983/TaraHouska_2017W-embed.jpg",
            speaker: "Tara Houska",
            title: "The Standing Rock resistance and our fight for indigenous rights",
            duration: 663.0,
            slug: "tara_houska_the_standing_rock_resistance_and_our_fight_for_indigenous_rights",
            viewed_count: 1037775,
          },
          {
            id: "22752",
            hero: "https://s3.amazonaws.com/talkstar-photos/uploads/e29ee9e0-0504-4bda-a4c9-e18409595a01/ChipColwell_2017X-embed.jpg",
            speaker: "Chip Colwell",
            title: "Why museums are returning cultural treasures",
            duration: 781.0,
            slug: "chip_colwell_why_museums_are_returning_cultural_treasures",
            viewed_count: 1425227,
          },
          {
            id: "2141",
            hero: "https://pe.tedcdn.com/images/ted/5b9e02089f8d97c645bc134ee83be65de49f72a4_2880x1620.jpg",
            speaker: "Mark Plotkin",
            title: "What the people of the Amazon know that you don't",
            duration: 995.0,
            slug: "mark_plotkin_what_the_people_of_the_amazon_know_that_you_don_t",
            viewed_count: 1596009,
          },
          {
            id: "2166",
            hero: "https://pe.tedcdn.com/images/ted/dde0408cf680c4eb3b140f8be034ce7b2c88bd38_2880x1620.jpg",
            speaker: "Tasso Azevedo",
            title: "Hopeful lessons from the battle to save rainforests",
            duration: 916.0,
            slug: "tasso_azevedo_hopeful_lessons_from_the_battle_to_save_rainforests",
            viewed_count: 940844,
          },
          {
            id: "2367",
            hero: "https://s3.amazonaws.com/talkstar-photos/uploads/9cf67f60-3ce4-4bc6-8340-fb6433056526/PatriciaMedici_2015F-embed.jpg",
            speaker: "Patrícia Medici",
            title: "The coolest animal you know nothing about ... and how we can save it",
            duration: 692.0,
            slug: "patricia_medici_the_coolest_animal_you_know_nothing_about_and_how_we_can_save_it",
            viewed_count: 1422885,
          },
        ],
        slug: "tashka_and_laura_yawanawa_the_amazon_belongs_to_humanity_let_s_protect_it_together",
        speakers: [
          {
            id: "2101",
            slug: "tashka_yawanawa",
            is_published: true,
            firstname: "Tashka and Laura",
            lastname: "Yawanawá",
            middleinitial: "",
            title: "",
            description: "Leaders of the Yawanawá",
            photo_url: "https://pe.tedcdn.com/images/ted/57e42c162b1c6e1dea28ef647852b2bc3296ce7d_254x191.jpg",
            whatotherssay:
              "Tashka inherently understands the forces at work in both his and the Western worlds. As a result, he serves as an unusually effective bridge between indigenous groups and the outside.",
            whotheyare:
              "Chief Tashka Yawanawá and Laura Yawanawá represent the critical perspective often missed in the discussions about the future of indigenous people in Brazil: that of the indigenous people themselves.",
            whylisten:
              "<p>For Tashka and Laura Yawanaw&aacute;, leaders of the Yawanaw&aacute; people living in the Acre region of Brazil, engagement with the world begins with his people&rsquo;s right to self-determination and self-worth.</p><p>The son of a former leader of the Yawanaw&aacute;, as a boy Tashka witnessed the near annihilation of his culture by the New Tribes Mission and by the pressure of economic interests. He studied in the United States and visited other indigenous communities. With other tribal leaders in the Amazon, he is working to restore dignity, identity and a sustainable economic future to indigenous populations, founded on their own values, culture and definition of prosperity.</p>",
          },
        ],
        speaker_name: "Tashka and Laura Yawanawá",
        tags: ["community", "conservation", "indigenous peoples", "humanity", "activism", "society", "social change", "South America"],
        title: "The Amazon belongs to humanity -- let's protect it together",
        video_type: { id: "1", name: "TED Stage Talk" },
        viewed_count: 13755,
      },
    ],
  },
});
